### ISSUE TITLE
Builds failing on Travis (500) but (sort of) run fine locally

### ISSUE THREAD

**Issue by atuttle** [marcins/cfml-ci#20]
I'm attempting to use this repo template to add Travis-CI testing to my project, but [something's not quite right](https://travis-ci.org/CounterMarch/moment.cfc/jobs/55575589#L289).

> [get] Error opening connection java.io.IOException: Server returned HTTP response code: 500 for URL: http://localhost:8888/momentcfc/tests/ci/testbox-runner.cfm?directory=momentcfc.tests.testbox&reporter=text&reportPath=/home/travis/build/CounterMarch/moment.cfc/tests/ci/results/

I tried running the same url locally, modified to work on my environment, and hoping it would just write the results to the screen: 

http://localhost/momentcfc/tests/ci/testbox-runner.cfm?directory=momentcfc.tests.testbox&reporter=text

Note that I modified my build.xml to include the project name in the directory argument: `testbox-runner.cfm?directory=${test.project}.${testbox.directory}` -- this would seem to be necessary, at least in the case of my project, because of the URL it's being installed to: `http://localhost:8888/momentcfc/` (from the error above). Using my modified URL, the tests run and pass -- though I'm on OSX and I'm not running via ant.

Initially this didn't go as well as I had hoped. I have a newer version of TestBox (downloaded in the last few days), and not only have some things been moved around (it would seem that `testbox.system.testing.TestBox` is now `testbox.system.TestBox`). I made some slight modifications to testbox-runner.cfm (default value for reportPath, dotted path for TestBox instance) and I also changed the remote URL for TestBox to the current version... Still, it's not building! :frowning:

Any ideas? They're not giving me much to go on: just a 500.

**Comment by seancorfield** [comment]
This path `/home/travis/build/CounterMarch/moment.cfc/tests/ci/results/` seems to have a `.` in it but this path `http://localhost:8888/momentcfc/tests/ci/testbox-runner.cfm` does not. Similarly `momentcfc.tests.testbox` doesn't have a `.` before `cfc` either.

**Comment by atuttle** [comment]
I might have misunderstood what that property was for... Now it's (back to) [failing only on ACF10](https://travis-ci.org/CounterMarch/moment.cfc/jobs/55579776#L127)...

**Comment by atuttle** [comment]
I think it's testing fine now, I just have some bugs in my code I need to resolve. Thanks, @seancorfield!
